### PR TITLE
Add module functions

### PR DESCRIPTION
**Pull request by LucyMcGowan**
Thank you so much for making this package! I have added a few functions

  * `create_canvas_module()`
  * `create_canvas_module_item()`
  * `get_module_list()`

I also fixed a small bug in `create_course_assignment()` and `create_course_folder()`

Feel free to ignore this if it is out of scope for the package but I thought I'd submit in case it is useful!

### CODE REVIEW

**Comment by pachadotdev** [comment]
looks good! thanks a lot

**Comment by daranzolin** [comment]
Super cool to see this! Thanks @LucyMcGowan and shout out to @pachadotdev for keeping this package going!

**Comment by LucyMcGowan** [comment]
Thank you for putting it together! It will save me so much time this semester!

**Comment by pachadotdev** [comment]
> Super cool to see this! Thanks @LucyMcGowan and shout out to @pachadotdev for keeping this package going!

thanks! I've been mostly watching issues, without doing much change

**Pull request merged**
